### ISSUE TITLE
Custom Biomes not converting from tainted lands, reloading makes them plains biomes. (Multiplayer)

### ISSUE THREAD

**Issue by Nekosity12** [Midnight145/blightfall-issue-tracker#25] opened 2023-02-08 03:29 UTC
I don't think them being plains has any real relevance, it just seems like mc defaults it to that because it needs the biome and the reason the biome stays tainted until it gets reloaded is because it can't convert into the custom biome.

Not converting & Reloading the chunks:
https://youtu.be/Y9fpfAHByVw
Plains Biomes where custom biomes should be:
https://youtu.be/Jelmh1DzhkM

V3.0.1-CE

Additional Information: We played before the update on the same server, all files were wiped and the updated files were uploaded.

**Comment by Midnight145** [comment] 2023-02-12 22:13
Still looking into this, trying to find the root cause

**Comment by Midnight145** [comment] 2023-02-15 02:02
Will be fixed next release

**Closed by Midnight145** 2023-02-15 02:03 UTC
