### ISSUE TITLE
Bloodwood no longer usable as special material

### ISSUE THREAD

**Issue by MarineRusher** [Midnight145/blightfall-issue-tracker#31] opened 2023-02-15 22:03 UTC
Tools made out of bloodwood now make regular wooden tools, and tools that were made out of bloodwood prior to update are now only repairable through the thaumic restorer/livingmoss or other non-material input ways to repair tools

**Comment by Midnight145** [comment] 2023-02-15 22:05
huh, I really thought I would've caught this. I'll fix this and put out a patch real quick. I assume the other nether woods are the same way?

**Comment by MarineRusher** [comment] 2023-02-15 22:09
Yes they are the same, just checked

**Comment by Midnight145** [comment] 2023-02-15 22:16
Alright, thank you. Not entirely sure what caused this, but I'll get on this ASAP.

**Comment by Midnight145** [comment] 2023-02-15 22:33
Root cause has been identified, working on a fix.

**Comment by Midnight145** [comment] 2023-02-15 22:43
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/9489681cbabfa1ed85447656616fe492d2b6eaf1), working on putting out a hotfix update

**Closed by Midnight145** 2023-02-15 22:43 UTC
