### ISSUE TITLE
Angmallen Smeltery Dupe

### ISSUE THREAD

**Issue by Nouonn** [Midnight145/blightfall-issue-tracker#21] opened 2023-02-05 18:01 UTC
https://youtu.be/Wd3XCjyLrCI

I somehow deactivated the glitch but was able to reactivate it again

Have som fun with this :)

**Comment by Midnight145** [comment] 2023-02-08 00:49
Video is private, can you set it to unlisted?

**Comment by Midnight145** [comment] 2023-02-08 07:13
Currently closing as I'm unable to reproduce, but if you find a consistent setup for it feel free to reopen.

**Closed** 2023-02-08 07:13 UTC
