### ISSUE TITLE
Dawn machine and botania sparks causing ticking entity crashes

### ISSUE THREAD

**Issue by MayliSong** [Midnight145/blightfall-issue-tracker#72] opened 2023-05-09 02:22 UTC
Noticing a running problem where certain actions with the dawn machine cause null pointer ticking entity crashes if there are mana sparks nearby. 

The crash was caused when trying to construct the dawn machine, add a spark to the dawn machine, or remove the spark from the machine, but ONLY if sparks were already placed on the nearby mana pools. Removing the sparks from the mana pools before doing any of those prevents the crash and then the sparks can be put back on the pools. 

All the crash logs list the ticking entity causing the crash as one of the sparks over the two mana pools. I have several logs but they all look near identical at a glance so I've only linked the most recent one. https://paste.ee/p/YwaGo

[EDIT] I forgot to mention that I have to load a backup to before the action causing the crash every time this happens, otherwise it will be stuck in a loop of crashing as soon as the game loads.

**Comment by Midnight145** [comment] 2023-07-01 20:57
I'm so sorry, I'm just now getting to this.
It looks like your paste expired, do you still have the old crashlog by chance?

**Comment by MayliSong** [comment] 2023-07-01 21:58
It’s likely that I have a few of them still with how multimc saves crash logs, and if I don’t I should be able to generate a new one easily since it was so easily recreated for me and I haven’t updated anything since, but I probably won’t be able to get the logs until tomorrow. Just wanted to say I saw this and will look at it, and no worries about it taking a while to get to it; I’d imagine most things in life probably come before modpack development/upkeep :)

**Comment by Midnight145** [comment] 2023-07-01 22:00
If you could grab one when you get a chance, that'd be great. Thank you!

**Comment by Midnight145** [comment] 2023-09-24 23:05
High key forgot about this. Did you ever manage to find one, or are you able to reproduce it?

**Comment by Midnight145** [comment] 2023-12-16 07:36
likely fixed in [this commit](https://github.com/Midnight145/blightbuster/commit/e57e4c03301332e6e82a208653344b7d93e2a411), feel free to reopen if it persists after the next patch

**Closed by Midnight145** 2023-12-16 07:36 UTC
Labels: bug, crash, blightbuster
