### ISSUE TITLE
Dawn machine misses small patches of blight

### ISSUE THREAD

**Issue by Hunter24681** [Midnight145/blightfall-issue-tracker#151] opened 2024-09-05 23:21 UTC
Blightfall Version: 3.1.1-CE

**Describe the bug**
Dawn machine is missing a handful of small (1-4px on scan map) blight spots.  Enough to prevent gold medal for clearing area

**To Reproduce**
Uncertain, but the blight spots all seem to be where tunnels from the arcane bore are made

**Expected behavior**
Machine should clear all blight as it encounters it

**Screenshots**
![2024-09-05_18 10 26](https://github.com/user-attachments/assets/d9867496-ded3-4deb-ac7d-6c1ca380a4cb)

**Additional context**
Initially occurred with machine close to the center of the island.  After noticing it, I moved closer (both overhead once and then a few hundred blocks north, as on my initial run the machine missed ~3x3 chunks directly underneath it), and let it run for 15-30 min.  Seeing that they were still there, I reran 2 more times in case there was a fluke, but none of the spots cleared.

This area of the map, I ran an arcane bore down to bedrock and then turned it sideways for a half-dozen tunnels at bedrock level.  I found a few splotches of blight in those tunnels and was able to use the purity focus to clear them, but I could find no more down there.  I'm not sure if the unusual terrain from the bore might have any impact

**Comment by Midnight145** [comment] 2024-09-05 23:23
likely duplicate of #62, will be fixed next patch

**Closed as completed by Midnight145** 2024-09-05 23:23 UTC
Labels: bug
